name: Update Language Stats

on:
  schedule:
    - cron: "0 6 * * 1"   # Montag 06:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v6

      - name: Python installieren
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: GitHub CLI installieren
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Script ausführen
        run: python scripts/update_languages.py
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Änderungen committen
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update language stats" || echo "No changes"
          git push